spring:
  application:
    name: PolyTrader

services:
  polymarket:
    wss_live_data_url: wss://ws-live-data.polymarket.com
    gamma_base_url: https://gamma-api.polymarket.com
    market_refresh_seconds: 1
  binance:
    base_url: https://api.binance.com
    wss_url: wss://stream.binance.com:9443/ws/
    api_key: ${BINANCE_API_KEY}
    secret: ${BINANCE_SECRET}
  coinbase:
    wss_url: wss://ws-feed.exchange.coinbase.com
  kraken:
    wss_url: wss://ws.kraken.com/v2
  bybit:
    wss_url: wss://stream.bybit.com/v5/public/spot
  okx:
    wss_url: wss://ws.okx.com:8443/ws/v5/public

trading:
  mock: true
  minimum-expected-ev: 1.25
  minimum-win-chance: 0.10
  taker-fee: 0.07
  mock-bet-amount: 1