# src/main/resources/application.yaml
spring:
  application:
    name: PolyTrader

logging:
  level:
    al.r1.polytrader.services.polymarket.PolymarketDataProvider: INFO

services:
  polymarket:
    wss_live_data_url: wss://ws-live-data.polymarket.com
    gamma_base_url: https://gamma-api.polymarket.com
    clob_wss_url: wss://ws-subscriptions-clob.polymarket.com/ws/market
    market-wss-url: wss://api.polymarket.us/v1/ws/markets
    api-key: ${POLYMARKET_API_KEY}
    api-key-address: ${POLYMARKET_API_KEY_ADDRESS}
    market_refresh_seconds: 1
  binance:
    base_url: https://api.binance.com
    wss_url: wss://stream.binance.com:9443/ws/
    api_key: ${BINANCE_API_KEY}
    secret: ${BINANCE_SECRET}

trading:
  mock: true
  minimum-expected-ev: 1.00
  minimum-win-chance: 0.20
  taker-fee: 0.07
  mock-bet-amount: 1
  minimum-seconds-since-open: 5