spring:
  application:
    name: PolyTrader

services_wss:
  coinbase: wss://ws-feed.exchange.coinbase.com
  kraken: wss://ws.kraken.com
  bybit: wss://stream.bybit.com/v5/public/spot
  okx: wss://ws.okx.com:8443/ws/v5/public.

binance:
  base_url: https://api.binance.com
  wss_url: wss://stream.binance.com:9443/ws/
  api_key: ${BINANCE_API_KEY}
  secret: ${BINANCE_SECRET}

polymarket:
  wss_live_data_url: wss://ws-live-data.polymarket.com
