[package]
name = "polymarket-executor-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
axum = "0.8"
dotenvy = "0.15"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

alloy = { version = "1", features = ["full"] }

polymarket_client_sdk_v2 = {
    git = "https://github.com/Polymarket/rs-clob-client-v2",
    rev = "222143d321eba97d5711a848265eb9aab3bc7ff4",
    features = ["clob"]
}

rust_decimal = "1"
rust_decimal_macros = "1"
chrono = "0.4"